### ISSUE TITLE
Design approval

### ISSUE THREAD

**Issue by darthkurten** [darthkurten/adailyexcuse#1]
We need to approve the design, then we can move on to de development.

here is the link to access the small prototype:
http://invis.io/9Y2C1ZDWT

Note that the final adjustments (hover states, proper aligning of the elements, etc.) will be made directly o html & css

**Comment by darthkurten** [comment]
I gess that the elements in the design could be smaller, will be tested in html & CSS.
Maybe this http://www.gradient-animator.com/ could be added to the header too.

**Comment by zehfernandes** [comment]
I made some notes for you consider.

![1](https://cloud.githubusercontent.com/assets/1891339/6453738/efd675f2-c11f-11e4-8efa-b2dc33bdaa5d.jpg)

![2](https://cloud.githubusercontent.com/assets/1891339/6453737/efd437f6-c11f-11e4-9321-737e9eefb3b9.jpg)

What you think?

**Comment by darthkurten** [comment]
I only add the footer to define it's style, don't know about the position.

I only disagree about the use of the mascot in the kudo button, i tried to
apply it and in the mobile devices the expressions on his face won't be
recognized due to the small size.

 I'll make the changes and upload it again.

Thx

2015-03-02 21:08 GMT-03:00 Zeh Fernandes notifications@github.com:

> I made some notes for you consider.
> 
> [image: 1]
> https://cloud.githubusercontent.com/assets/1891339/6453738/efd675f2-c11f-11e4-8efa-b2dc33bdaa5d.jpg
> 
> [image: 2]
> https://cloud.githubusercontent.com/assets/1891339/6453737/efd437f6-c11f-11e4-9321-737e9eefb3b9.jpg
> 
> What you think?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darthkurten/adailyexcuse/issues/1#issuecomment-76859248
> .

## 

Guilherme Kürten
Designer Gráfico

Portfolio: behance.net/kurten http://www.behance.net/kurten

Telefone: (41) 84000588
facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

**Comment by darthkurten** [comment]
new version:

http://invis.io/ZR2CFXYQC

what do you guys think?

There's some actions (like the change in the "copy text" button when you
click on it) that i think that we should address in the HTML & CSS step,
it'll be faster to iterate i gess (only text and icon changes).

Thx, i'll wait for the feedback to start the front-end

2015-03-02 21:21 GMT-03:00 Guilherme Kurten guilherme.krten@gmail.com:

> I only add the footer to define it's style, don't know about the position.
> 
> I only disagree about the use of the mascot in the kudo button, i tried to
> apply it and in the mobile devices the expressions on his face won't be
> recognized due to the small size.
> 
>  I'll make the changes and upload it again.
> 
> Thx
> 
> 2015-03-02 21:08 GMT-03:00 Zeh Fernandes notifications@github.com:
> 
> I made some notes for you consider.
> 
> > [image: 1]
> > https://cloud.githubusercontent.com/assets/1891339/6453738/efd675f2-c11f-11e4-8efa-b2dc33bdaa5d.jpg
> > 
> > [image: 2]
> > https://cloud.githubusercontent.com/assets/1891339/6453737/efd437f6-c11f-11e4-9321-737e9eefb3b9.jpg
> > 
> > What you think?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/darthkurten/adailyexcuse/issues/1#issuecomment-76859248
> > .
> 
> ## 
> 
> Guilherme Kürten
> Designer Gráfico
> 
> Portfolio: behance.net/kurten http://www.behance.net/kurten
> 
> Telefone: (41) 84000588
> facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

## 

Guilherme Kürten
Designer Gráfico

Portfolio: behance.net/kurten http://www.behance.net/kurten

Telefone: (41) 84000588
facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

**Comment by BaddestMojo** [comment]
Ok, first of all: I am not a designer so please disregard any amateur comments. I'm going to give you an input based on an user standpoint, and any and all things design (the ones you guys know A LOT better than me) should be taken into consideration before that.

![excuses1](https://cloud.githubusercontent.com/assets/11297647/6468943/8cd35b9e-c1b7-11e4-9828-3cd1a0a8a790.jpg)

That being said, here's what I think:
- I agree with Zé on the information conflicting with the content. In fact, I strongly suggest we give more importance to the content at hand. For me, it works better if the unrelated information (such as the "about" "pt/en" buttons) are incorporated into the header or the footer. Just a suggestion.
- Also on the content end: my impression is that the header takes too much space, as well as the empty margins, making the focus area of the actual content smaller, less intuitive and taking away its emphasis. I would, again, prefer a more prominent central content area.
- I understand the language and the importance of a mascot (or brand) in projects like these. As so, I think both the language AND the mascot could be strengthened. I'm guessing that, like GourmetStrike, this project will have a small intro focusing on the design at hand. But with a smaller header, the brand could have more evidence. I also think that we could find a way to use a simplified version of the mascot to get around the size problem in mobile apps (as said about the rating faces).

Here´s an idea of my sugestions :)

![excuses2](https://cloud.githubusercontent.com/assets/11297647/6469047/219c295e-c1b8-11e4-9779-39587f7a8e58.jpg)

**Comment by gui-santos** [comment]
![layout_test](https://cloud.githubusercontent.com/assets/6597467/6469067/43f08bd0-c1b8-11e4-9ba5-67199bdab2e8.png)

I tryed to improve the upvoted icon based in Zeh's sugestions. I think we could use him in a simplified version. The active state would be the mascot smiling and yellow and the normal state would be it gray (??) and sad.

Also, the facebook button was giving me an impression of inconsistency

And about the header, I really liked the suggestions made by BaddestMojo! I think we should incorporate those changes

**Comment by gui-santos** [comment]
Ah! I forgot to say something:

Shouldn't we drop the black color and use the blue (purpleish) instead? (I mean in the texts)

Are we going to display all the excuses as e-mails?

I prefer to display just like we did in gourmet strike... The text alone without any formatting

**Comment by darthkurten** [comment]
First, addressing the margin issue:
- The margins are that wide because i design it to fit a 1366px wide
  screen using a 1920px canvas. I strongly suggest that on that size, (and in
  bigger screens) that margin area be preserved, for better readability.

On the header issue:
- About the size and menu i agree, i'll test it and get back to you guys
  with a new layout.

On the mascot
- I totally agree, but since it'll be used mostly in the header i gess
  that we could use the same one throughout the different resolutions.

On the share icons.
- I know it feels unbalanced visually, but i think that using the
  "facebook blue" helps to identify the function of the button, but the "f"
  icon could be enough. I'll incorporate to the design, and we can change it
  in the HTML & CSS prototype

On the upvoted
- i gess that we could use that colored representation on the "upvoted"
  icon. the repetition of the yellow icon on the first page may be too much.

---

I forgot to incorporate the ""see the excuse" button on the design, i'll do
it too.

---

Tonight i'll have the latest iteration of the design =D

2015-03-03 15:24 GMT-03:00 Guilherme Gonçalves notifications@github.com:

> [image: layout_test]
> https://cloud.githubusercontent.com/assets/6597467/6469067/43f08bd0-c1b8-11e4-9ba5-67199bdab2e8.png
> 
> I tryed to improve the upvoted icon based in Zeh's sugestions. I think we
> could use him in a simplified version. The active state would be the mascot
> smiling and yellow and the normal state would be it gray (??) and sad.
> 
> Also, the facebook button was giving me an impression of inconsistency
> 
> And about the header, I really liked the suggestions made by BaddestMojo!
> I think we should incorporate those changes
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darthkurten/adailyexcuse/issues/1#issuecomment-77003478
> .

## 

Guilherme Kürten
Designer Gráfico

Portfolio: behance.net/kurten http://www.behance.net/kurten

Telefone: (41) 84000588
facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

**Comment by darthkurten** [comment]
About the text:
- idk, i think that we could have a generic text, just used the email
  template, but have no issues about demonstrating just the plain text.

2015-03-03 15:42 GMT-03:00 Guilherme Kurten guilherme.krten@gmail.com:

> First, addressing the margin issue:
> - The margins are that wide because i design it to fit a 1366px wide
>   screen using a 1920px canvas. I strongly suggest that on that size, (and in
>   bigger screens) that margin area be preserved, for better readability.
> 
> On the header issue:
> - About the size and menu i agree, i'll test it and get back to you
>   guys with a new layout.
> 
> On the mascot
> - I totally agree, but since it'll be used mostly in the header i gess
>   that we could use the same one throughout the different resolutions.
> 
> On the share icons.
> - I know it feels unbalanced visually, but i think that using the
>   "facebook blue" helps to identify the function of the button, but the "f"
>   icon could be enough. I'll incorporate to the design, and we can change it
>   in the HTML & CSS prototype
> 
> On the upvoted
> - i gess that we could use that colored representation on the
>   "upvoted" icon. the repetition of the yellow icon on the first page may be
>   too much.
> 
> ---
> 
> I forgot to incorporate the ""see the excuse" button on the design, i'll
> do it too.
> 
> ---
> 
> Tonight i'll have the latest iteration of the design =D
> 
> 2015-03-03 15:24 GMT-03:00 Guilherme Gonçalves notifications@github.com:
> 
> [image: layout_test]
> 
> > https://cloud.githubusercontent.com/assets/6597467/6469067/43f08bd0-c1b8-11e4-9ba5-67199bdab2e8.png
> > 
> > I tryed to improve the upvoted icon based in Zeh's sugestions. I think we
> > could use him in a simplified version. The active state would be the mascot
> > smiling and yellow and the normal state would be it gray (??) and sad.
> > 
> > Also, the facebook button was giving me an impression of inconsistency
> > 
> > And about the header, I really liked the suggestions made by BaddestMojo!
> > I think we should incorporate those changes
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/darthkurten/adailyexcuse/issues/1#issuecomment-77003478
> > .
> 
> ## 
> 
> Guilherme Kürten
> Designer Gráfico
> 
> Portfolio: behance.net/kurten http://www.behance.net/kurten
> 
> Telefone: (41) 84000588
> facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

## 

Guilherme Kürten
Designer Gráfico

Portfolio: behance.net/kurten http://www.behance.net/kurten

Telefone: (41) 84000588
facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

**Comment by darthkurten** [comment]
Design lacking hierarqy, i'll try to fix today too. I'll take a more caring attitude towards design in fact, cos' this was a quick project i was kinda' trowing shit at the screen. Without taking some minor concerns about it.

**Comment by zehfernandes** [comment]
Some notes:
- I appreciate the blink draft that use the mascot to break the header square
- The @EpicCheddar simple vote version. Kudos haha 
- Like you sad @darthkurten the layout is in the middle way of a draft and close to finish. I really like the direction that you start to put, but It's important think if you want something more close to a draft style: 
  http://cannedemails.com/#
  or something focuses just in the typography 
  https://ia.net/know-how
  or the idea of a strong mascot brand and user improvements.

**Comment by darthkurten** [comment]
Hey guys, made the changes that you guys suggested. Since i tested new
colour schemes and some new controls of the navigation i did just the first
one.

Tomorrow i'll do the rest, but i would really appreciate your opinion on
this one (my personal choice would be the white header with the "plus" icon
beside the phrase):

http://invis.io/DX2CUKHAC

I incorporated the menu to the header in the same way that was done in the
gourmetstrike, really think that this project could share that type of
navigation (bringing some consistency to the users from gourmetstrike too)

Also, i like to add that i think that the hover states should have tiny animations (like "vote me" or "pleaase" over the upvote, and a "thank you" or a little heart poppin' up when the person click it.)

addressing some of the changes that were not implemented:
- Tried to add a button that would link to the excuse, but the length
  difference between the sentences could become a problem (specially in
  smaller sizes)

BTW i gess that i'll give another shot at the typography, still unhappy with the final results

Thx guys =D

2015-03-03 21:48 GMT-03:00 Zeh Fernandes notifications@github.com:

> Some notes:
> - I appreciate the blink draft that use the mascot to break the header
>   square
> - The @EpicCheddar https://github.com/EpicCheddar simple vote
>   version. Kudos haha
> - Like you sad @darthkurten https://github.com/darthkurten the
>   layout is in the middle way of a draft and close to finish. I really like
>   the direction that you start to put, but It's important think if you want
>   something more close to a draft style: http://cannedemails.com/# or
>   something focuses just in the typography https://ia.net/know-how or
>   the idea of a strong mascot brand and user improvements.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darthkurten/adailyexcuse/issues/1#issuecomment-77075239
> .

## 

Guilherme Kürten
Designer Gráfico

Portfolio: behance.net/kurten http://www.behance.net/kurten

Telefone: (41) 84000588
facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

**Comment by darthkurten** [comment]
Made the last iteration.

Adopted the white header and simplified all the elements involved in the composition.

http://invis.io/832D8GFFR

I'll wait for feedbacks to target other tasks.

**Comment by gui-santos** [comment]
I liked it a lot!

_Guilherme Gonçalves Santos_

_behance.net/guilhermegs https://www.behance.net/guilhermegs_
guilherme.goncalvessantos@gmail.com
Fone: (41) 9945 8926
Skype: gui_gsantos

2015-03-04 23:07 GMT-03:00 Guilherme Kurten notifications@github.com:

**Comment by thiagogrossmann** [comment]
I finally read all the replies ( some yay for me).

So, i liked the last version,, liked the colors and everything, considerations:
- I'm the only one who didn't get the "vote" thing? why you vote? what's the reason ? (sorry for my stupidity)
- Have you thought about using only lines on the mascot?

**Comment by darthkurten** [comment]
- I gess that when the users see the ranking working they'll get the
  numbers and the vote, ( i don't really know the difficulty that is to make
  a live ranking in the back end).
- One solution is to add a "ranking" label over that area, but i think
    that's unnecessary,
  - Bout the mascot
  - I did thought about it, but think that the animation will thrive in
    the coloured mascot. Besides, i like the idea of a little moreo
    colour and
    personality in the design.

2015-03-05 16:55 GMT-03:00 thiagogrossmann notifications@github.com:

> I finally read all the replies ( some yay for me).
> 
> So, i liked the last version,, liked the colors and everything,
> considerations:
> 
>    -
> 
>    I'm the only one who didn't get the "vote" thing? why you vote? what's
>    the reason ? (sorry for my stupidity)
>    -
> 
>    you think about using only lines on the mascot?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darthkurten/adailyexcuse/issues/1#issuecomment-77438891
> .

## 

Guilherme Kürten
Designer Gráfico

Portfolio: behance.net/kurten http://www.behance.net/kurten

Telefone: (41) 84000588
facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

**Comment by darthkurten** [comment]
Talking with @thiagogrossmann the issue he has with the voting system is
that he doesn't get it that the "sad expression" means the "unvoted" state.
- personally I think that's a valid point that should be tested in the
  mark-up phase.

2015-03-05 17:05 GMT-03:00 Guilherme Kurten guilherme.krten@gmail.com:

> - I gess that when the users see the ranking working they'll get the
>   numbers and the vote, ( i don't really know the difficulty that is to make
>   a live ranking in the back end).
> - One solution is to add a "ranking" label over that area, but i think
>     that's unnecessary,
>   - Bout the mascot
>   - I did thought about it, but think that the animation will thrive
>     in the coloured mascot. Besides, i like the idea of a little moreo colour
>     and personality in the design.
> 
> 2015-03-05 16:55 GMT-03:00 thiagogrossmann notifications@github.com:
> 
> I finally read all the replies ( some yay for me).
> 
> > So, i liked the last version,, liked the colors and everything,
> > considerations:
> > 
> >    -
> > 
> >    I'm the only one who didn't get the "vote" thing? why you vote?
> >    what's the reason ? (sorry for my stupidity)
> >    -
> > 
> >    you think about using only lines on the mascot?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/darthkurten/adailyexcuse/issues/1#issuecomment-77438891
> > .
> 
> ## 
> 
> Guilherme Kürten
> Designer Gráfico
> 
> Portfolio: behance.net/kurten http://www.behance.net/kurten
> 
> Telefone: (41) 84000588
> facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

## 

Guilherme Kürten
Designer Gráfico

Portfolio: behance.net/kurten http://www.behance.net/kurten

Telefone: (41) 84000588
facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

**Comment by darthkurten** [comment]
Hey guys, lets move on

Last night i was talking with gui, and he said that he wanted to do the
dailyexcuse in angular, what do you guys think? ( i gess that @zehfernandes
is the only one that could provide further insight over the matter)
​

**Comment by zehfernandes** [comment]
So, about angular. Let's do it. We are here to learn new things :smile: 

The layout, I like the last version. 
Some final adjustments we can do direct in the code. 
@darthkurten start spread the tasks

**Comment by darthkurten** [comment]
i'll do that.

Gui told me that he want to handle the front-end too. So i gess that'll
help with media queries and such.
Anyway, tonight i'll do it.

=D

2015-03-09 11:26 GMT-03:00 Zeh Fernandes notifications@github.com:

> So, about angular. Let's do it. We are here to learn new things [image:
> :smile:]
> 
> The layout, I like the last version.
> Some final adjustments we can do direct in the code.
> @darthkurten https://github.com/darthkurten start spread the tasks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darthkurten/adailyexcuse/issues/1#issuecomment-77862640
> .

## 

Guilherme Kürten
Designer Gráfico

Portfolio: behance.net/kurten http://www.behance.net/kurten

Telefone: (41) 84000588
facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

**Comment by thiagogrossmann** [comment]
don't know what it is, but, let's do it!

**Comment by darthkurten** [comment]
Done it, if there's something off, let me know. Thx

2015-03-09 18:40 GMT-03:00 thiagogrossmann notifications@github.com:

> don't know what it is, but, let's do it!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darthkurten/adailyexcuse/issues/1#issuecomment-77949148
> .

## 

Guilherme Kürten
Designer Gráfico

Portfolio: behance.net/kurten http://www.behance.net/kurten

Telefone: (41) 84000588
facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

**Comment by gui-santos** [comment]
Now that I'm working on the front-end I can started to see some need for adjustments in the design:

The upvote:

> We designed it with three-digit numbers, but what happens with no votes or two-digit numbers? Things start to lose their alignments;

The Excuse-List

> Maybe the entire line should be a link for the detailed excuse page (not just the plus button). A hover-state would also help to differentiate an excuse from another in the list

**Comment by darthkurten** [comment]
Yeah, i planned that way, but i thought that would be faster if we just put
the hover states through css. That's why there's no hover states in the
mock-up at all.

2015-03-21 1:34 GMT-03:00 Guilherme Gonçalves notifications@github.com:

> Now that I'm working on the front-end I can started to see some need for
> adjustments in the design:
> 
> The upvote:
> 
> We designed it with three-digit numbers, but what happens with no votes or
> two-digit numbers? Things start to lose their alignments;
> 
> The Excuse-List
> 
> Maybe the entire line should be a link for the detailed excuse page (not
> just the plus button). A hover-state would also help to differentiate an
> excuse from another in the list
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darthkurten/adailyexcuse/issues/1#issuecomment-84254109
> .

## 

Guilherme Kürten
Designer Gráfico

Portfolio: behance.net/kurten http://www.behance.net/kurten

Telefone: (41) 84000588
facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten

**Comment by gui-santos** [comment]
Well, sorry then! hahahaha I'm stupid

_Guilherme Gonçalves Santos_

_behance.net/guilhermegs https://www.behance.net/guilhermegs_
guilherme.goncalvessantos@gmail.com
Fone: (41) 9945 8926
Skype: gui_gsantos

2015-03-21 2:49 GMT-03:00 Guilherme Kurten notifications@github.com:

**Comment by darthkurten** [comment]
Nah, i should've added or at least explained.

2015-03-21 13:00 GMT-03:00 Guilherme Gonçalves notifications@github.com:

> Well, sorry then! hahahaha I'm stupid
> 
> _Guilherme Gonçalves Santos_
> 
> _behance.net/guilhermegs https://www.behance.net/guilhermegs_
> guilherme.goncalvessantos@gmail.com
> Fone: (41) 9945 8926
> Skype: gui_gsantos
> 
> 2015-03-21 2:49 GMT-03:00 Guilherme Kurten notifications@github.com:
> 
> > Yeah, i planned that way, but i thought that would be faster if we just
> > put
> > the hover states through css. That's why there's no hover states in the
> > mock-up at all.
> > 
> > 2015-03-21 1:34 GMT-03:00 Guilherme Gonçalves <notifications@github.com
> > :
> > 
> > > Now that I'm working on the front-end I can started to see some need
> > > for
> > > adjustments in the design:
> > > 
> > > The upvote:
> > > 
> > > We designed it with three-digit numbers, but what happens with no votes
> > > or
> > > two-digit numbers? Things start to lose their alignments;
> > > 
> > > The Excuse-List
> > > 
> > > Maybe the entire line should be a link for the detailed excuse page
> > > (not
> > > just the plus button). A hover-state would also help to differentiate
> > > an
> > > excuse from another in the list
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/darthkurten/adailyexcuse/issues/1#issuecomment-84254109
> > 
> > > .
> > 
> > ## 
> > 
> > Guilherme Kürten
> > Designer Gráfico
> > 
> > Portfolio: behance.net/kurten http://www.behance.net/kurten
> > 
> > Telefone: (41) 84000588
> > facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/darthkurten/adailyexcuse/issues/1#issuecomment-84260734
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darthkurten/adailyexcuse/issues/1#issuecomment-84377663
> .

## 

Guilherme Kürten
Designer Gráfico

Portfolio: behance.net/kurten http://www.behance.net/kurten

Telefone: (41) 84000588
facebook/guilherme.kurten http://www.facebook.com/guilherme.kurten
