### ISSUE TITLE
Back-end development

### ISSUE THREAD

**Issue by darthkurten** [darthkurten/adailyexcuse#5]
I gess that phase will only start after the mark up phase.

**Comment by gui-santos** [comment]
Well, I've prepared the basic angular. But I think the logic is dumb. Right now we are getting all the content from the app.js

This is going to be a pain in the ass for future updates and is some shitty job.

Soooooo.... We need to build some table in google drive (I don't know) and import the data from it to the app.js.... Maybe using JSON ?!?!?!

I'm going to take a look at this tomorrow

**Comment by zehfernandes** [comment]
You choose brow.

We can use:
- MEAN (MongoDB, Express, Angular and Node)
- NodeJS and Google Drive like Gourmet strike
- Mysql and PHP returning json

**Comment by darthkurten** [comment]
How that's going guys? Do you need anything?

**Comment by gui-santos** [comment]
I'm going to try to get Node and Angular running tonight

_Guilherme Gonçalves Santos_

_behance.net/guilhermegs https://www.behance.net/guilhermegs_
guilherme.goncalvessantos@gmail.com
Fone: (41) 9945 8926
Skype: gui_gsantos

2015-03-31 18:33 GMT-03:00 Guilherme Kurten notifications@github.com:
